# must specify
model: # TODO fill this in
dataset: # TODO fill this in
iterator: # TODO fill this in

batch_size: 5
num_steps: 1001
lr : 1.0e-4  # yaml needs 1.0 for exponential notation
lr_decay_begin : 1000 # TODO remove these in future versions
lr_decay_end : 1001  # TODO remove these in future versions


# options
spatial_size: 28
log_freq : 10
ckpt_freq: 100

# cd edflow/examples
# run with edflow -t mnist_tf/train.yaml -n mnist_tf